# NovaFlare Engine - FlxSound null-pointer crash fixes (2 patches)
#
# Crash evidence (novaflare-native-crash-v1 native crash log):
#   SIGSEGV / fault_address=0x30, faulting instruction `str d0, [x8, #0x30]`, x8 == NULL.
#   Reverse engineering identified flixel::sound::FlxSound_obj::updateTransform():
#   it dereferences this->_transform (object offset +0xd8); SoundTransform.volume is at +0x30.
#
#   Call chain: Lua playSound/setSoundVolume -> FunkinLua closure -> SoundFrontEnd.play
#               -> FlxSound.set_volume -> FlxSound.updateTransform   (crash site)
#
#   _transform is only ever nulled by FlxSound.destroy(). Two independent ways of reaching
#   updateTransform() with a null _transform exist, and BOTH are patched here:
#
#   PATCH 1 (updateTransform guard)
#     destroy() sets _transform = null, but SoundFrontEnd.destroy() (called on every state
#     switch via FlxGame.hx:715) destroys the sounds in FlxG.sound.list WITHOUT removing
#     them, so list.recycle() later reuses those already-destroyed instances and Lua may
#     still hold references. Any updateTransform() call then writes to NULL+0x30.
#
#   PATCH 2 (loadEmbedded empty-asset reset)
#     When the asset is missing, SoundFrontEnd.play()'s cache() returns null; the original
#     loadEmbedded() returned early at that point, skipping cleanup(true) -> reset(), which
#     is the only place that recreates _transform. SoundFrontEnd.play() then calls
#     loadHelper() -> `sound.volume = volume` -> set_volume -> updateTransform -> crash.
#     The patch resets state (cleanup(true) rebuilds _transform) before returning.
#
# NOTE: the patch text inserted into FlxSound.hx is deliberately ASCII-only. PowerShell 5.1
#       reads a BOM-less .ps1 as ANSI/GBK, and multi-byte characters inside these string
#       literals were mis-parsed (a Chinese arrow broke the tokenizer), so keep them ASCII.
#
# Usage:
#   powershell -File tools\patch-flxsound-null-guard.ps1 -Status   # show state
#   powershell -File tools\patch-flxsound-null-guard.ps1 -Apply    # apply both patches
#   powershell -File tools\patch-flxsound-null-guard.ps1 -Revert   # revert both patches
#
# IMPORTANT: /dependencies/ is listed in .gitignore. FlxSound.hx is force-added to the
#            repository (-f), so a normal clone already contains the fix. This script is for
#            the case where dependencies get regenerated by `hmm install` or a dependency
#            update, which would overwrite the patched file.

[CmdletBinding()]
param(
  [switch]$Apply,
  [switch]$Revert,
  [switch]$Status
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$candidates = @(
  (Join-Path $projectRoot 'dependencies\flixel-5.9.0-main\flixel\sound\FlxSound.hx'),
  (Join-Path $projectRoot '.haxelib\flixel\5,9,0\flixel\sound\FlxSound.hx'),
  (Join-Path $projectRoot '.haxelib\flixel\6,1,2\flixel\sound\FlxSound.hx')
)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Read-Text([string]$p) { return [System.IO.File]::ReadAllText($p, $utf8NoBom) }
function Write-Text([string]$p, [string]$t) { [System.IO.File]::WriteAllText($p, $t, $utf8NoBom) }
function NewlineOf([string]$t) { if ($t.Contains("`r`n")) { return "`r`n" } else { return "`n" } }
function Test-Applied([string]$t) { return ($t.Contains('>>> NovaFlare fix 1') -and $t.Contains('>>> NovaFlare fix 2')) }

function Get-TargetPath {
  foreach ($c in $candidates) { if (Test-Path -LiteralPath $c) { return $c } }
  throw ("FlxSound.hx not found. Tried:" + [Environment]::NewLine + ($candidates -join [Environment]::NewLine))
}

# ---- anchors (adjust here if the upstream file changes) ----
$anchor1 = "`tfunction updateTransform():Void`n`t{`n`t`t_transform.volume ="
$anchor2 = @"
	public function loadEmbedded(EmbeddedSound:FlxSoundAsset, Looped:Bool = false, AutoDestroy:Bool = false, ?OnComplete:Void->Void):FlxSound
	{
		if (EmbeddedSound == null)
			return this;
			
		cleanup(true);
"@

function Get-Block1([string]$nl) {
  @(
    "`t`t// >>> NovaFlare fix 1: updateTransform() null guard",
    "`t`t// destroy() nulls _transform, but SoundFrontEnd.destroy() leaves the destroyed",
    "`t`t// sounds inside FlxG.sound.list, so list.recycle() may reuse them and Lua may still",
    "`t`t// hold references. Dereferencing _transform then writes NULL+0x30 and raises a",
    "`t`t// native SIGSEGV (fault_address=0x30). Return defensively here; do NOT recreate",
    "`t`t// _transform, so the destroyed state stays visible instead of being masked.",
    "`t`tif (_transform == null)",
    "`t`t`treturn;",
    "`t`t// <<< NovaFlare fix 1",
    ""
  ) -join $nl
}

function Get-Block2([string]$nl) {
  @(
    "`t`t// >>> NovaFlare fix 2: rebuild _transform when the asset is empty",
    "`t`t// The original code returned right here, skipping cleanup(true) -> reset(), which",
    "`t`t// is the only place that recreates _transform. SoundFrontEnd.play() then calls",
    "`t`t// loadHelper() -> sound.volume = volume -> set_volume -> updateTransform, which",
    "`t`t// dereferences the null _transform and raises SIGSEGV (fault_address=0x30).",
    "`t`t// Reset the state first, then report the sound as unloaded.",
    "`t`tif (EmbeddedSound == null)",
    "`t`t{",
    "`t`t`tcleanup(true);",
    "`t`t`t_sound = null;",
    "`t`t`texists = false;",
    "`t`t`treturn this;",
    "`t`t}",
    "`t`t// <<< NovaFlare fix 2",
    ""
  ) -join $nl
}

$path = Get-TargetPath

if ($Status -or (-not $Apply -and -not $Revert)) {
  $text = Read-Text $path
  Write-Host "File  : $path"
  if (Test-Applied $text) {
    Write-Host "Status: FULLY FIXED (patch 1 + patch 2)" -ForegroundColor Green
  } elseif ($text.Contains('if (_transform == null)')) {
    Write-Host "Status: PARTIALLY FIXED (only patch 1; the loadEmbedded empty-asset path still crashes)" -ForegroundColor Yellow
  } else {
    Write-Host "Status: NOT FIXED" -ForegroundColor Yellow
  }
  return
}

if ($Revert) {
  $text = Read-Text $path
  if (-not (Test-Applied $text)) { Write-Host "Not fully patched, nothing to revert."; return }
  $nl = NewlineOf $text
  $text = $text.Replace((Get-Block1 $nl), '')
  $text = $text.Replace((Get-Block2 $nl), '')
  Write-Text $path $text
  Write-Host "Reverted both patches: $path" -ForegroundColor Yellow
  return
}

if ($Apply) {
  $text = Read-Text $path
  $nl = NewlineOf $text
  if (Test-Applied $text) { Write-Host "Already fully patched, nothing to do." -ForegroundColor Green; return }

  if (-not $text.Contains($anchor1)) { throw "anchor 1 (updateTransform) not found - flixel source changed, patch manually." }
  $text = $text.Replace($anchor1, (Get-Block1 $nl) + "`t`t_transform.volume =")

  if (-not $text.Contains($anchor2)) { throw "anchor 2 (loadEmbedded) not found - flixel source changed, patch manually." }
  $text = $text.Replace($anchor2, (Get-Block2 $nl) + "`t`tcleanup(true);")

  Write-Text $path $text
  Write-Host "Applied patch 1 + patch 2: $path" -ForegroundColor Green
  Write-Host "Rebuild both exports:"
  Write-Host "  haxelib run lime build windows -release -D legacy_gc_compare"
  Write-Host "  haxelib run lime build android -D legacy_gc_compare"
}
